name: Build and upload

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        runners:
          - runner: UbuntuLatest32Cores128G
            system: x86_64-linux

          - runner: UbuntuLatest32Cores128GArm
            system: aarch64-linux

    runs-on: ${{ matrix.runners.runner }}
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/determinate-nix-action@v3

      - uses: DeterminateSystems/flakehub-cache-action@main

      - run: nix build .#packages.${{ matrix.runners.system }}.iso

      - uses: actions/upload-artifact@v4
        with:
          name: nixos-with-determinate-${{ matrix.runners.system }}.iso
          path: ./result/iso/*
          retention-days: 90
